/**
 * Subject cover helpers — no React, so they are unit tested.
 *
 * A cover is either a real image (subjects.image_url, generated by the AI) or
 * the instant fallback below: a gradient plus an emoji derived from the course
 * name. The fallback is deterministic, so the same subject always looks the
 * same and nothing has to be downloaded.
 */

export type SubjectCover = {
  /** css background for the tile */
  background: string;
  /** foreground colour that stays readable on `background` */
  color: string;
  /** soft ring/border colour */
  ring: string;
  emoji: string;
};

/** FNV-1a — small, stable, and spreads Arabic + English names evenly. */
export function subjectHash(name: string): number {
  let h = 0x811c9dc5;
  for (let i = 0; i < name.length; i++) {
    h ^= name.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

/** Keywords win over the hash so a Calculus cover reads as maths, not noise. */
const KEYWORDS: { match: RegExp; emoji: string }[] = [
  { match: /(math|calc|algebra|geom|riyl|riemann|integral|mathemat|ماث|حساب|جبر|هندس|تفاضل|تكامل)/i, emoji: "📐" },
  { match: /(phys|mechanic|optic|wave|thermo|فيزياء|ميكانيكا|بصريات|موجات|حرارة)/i, emoji: "⚛️" },
  { match: /(chem|organic|react|كيمياء|تفاعل|عضوي)/i, emoji: "🧪" },
  { match: /(bio|anatom|gene|cell|بيولوج|أحياء|تشريح|جيني)/i, emoji: "🧬" },
  { match: /(program|code|software|comput|algorithm|data|برمجه|حاسب|سيبر|خوارز|بيانات)/i, emoji: "💻" },
  { match: /(data|stat|machine|ai|learn|إحصاء|بيانات|تعلم|ذكاء)/i, emoji: "📊" },
  { match: /(network|database|web|cloud|شبك|قاعده|موقع|سحاب)/i, emoji: "🌐" },
  { match: /(lang|english|arabic|ترجمه|لغه|انجليزي|عربي)/i, emoji: "🗣️" },
  { match: /(history|geo|politic|تاريخ|جغرافيا|سياسه)/i, emoji: "🗺️" },
  { match: /(econom|account|finance|manage|business|اقتصاد|محاسبه|مال|ادارة|تجاره)/i, emoji: "📈" },
  { match: /(law|justice|قانون|عدل)/i, emoji: "⚖️" },
  { match: /(art|draw|design|music|فن|رسم|تصميم|موسيقي)/i, emoji: "🎨" },
  { match: /(relig|islam|christ|دين|اسلام|مسيح)/i, emoji: "📖" },
  { match: /(sport|phys.ed|رياضه|لياقه)/i, emoji: "⚽" },
  { match: /(psycho|neuro|social|نفس|عصبي|اجتماع)/i, emoji: "🧠" },
];

const FALLBACK_EMOJI = ["📚", "🗂️", "✏️", "🔬", "🧭", "📐", "🎯", "🧩", "🔭", "🧪", "📎", "🌱"];

/** Emoji that matches the subject name, or a stable one from its hash. */
export function subjectEmoji(name: string): string {
  const hit = KEYWORDS.find((k) => k.match.test(name));
  if (hit) return hit.emoji;
  return FALLBACK_EMOJI[subjectHash(name) % FALLBACK_EMOJI.length];
}

/**
 * Two-tone gradient. The hue comes from the name, the second stop is shifted so
 * the tile never looks flat, and saturation/lightness stay in a band that keeps
 * white text readable in both themes.
 */
export function subjectCover(name: string): SubjectCover {
  const h = subjectHash((name ?? "").trim() || "jadwali");
  const hue = h % 360;
  // Unsigned shifts: `>>` would go negative above 2^31 and emit hsl(-6 …).
  const hue2 = (hue + 40 + ((h >>> 8) % 60)) % 360;
  const sat = 62 + ((h >>> 4) % 16);
  return {
    background: `linear-gradient(135deg, hsl(${hue} ${sat}% 46%), hsl(${hue2} ${sat - 8}% 34%))`,
    color: "#fff",
    ring: `hsl(${hue} ${sat}% 46% / 0.35)`,
    emoji: subjectEmoji(name),
  };
}

/** True when the value is a usable image URL we are willing to put in <img src>. */
export function safeImageUrl(raw: string | null | undefined): string {
  const u = (raw ?? "").trim();
  if (!u) return "";
  if (!/^https?:\/\//i.test(u)) return "";
  try {
    return new URL(u).href ? u : "";
  } catch {
    return "";
  }
}
